cc_binary(
    name = "run_lidar_detection",
    srcs = ["run_lidar_detection.cc"],
    deps = ["@pcl//:common",
        "//mediapipe/calculators/ouster:os1",
        "//mediapipe/calculators/ouster:os1_util",
        "@com_github_open_source_parsers_jsoncpp//:jsoncpp",
    ],
)

